feature/crud shopping cart
wecode-bootcamp-korea/46-1st-WePet-backend pull request #4
Opened 2023-06-01 12:17 UTC by ts-oh

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.
<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 그리고 상세 내역을 적어주세요.
- add post request to add items to shopping cart
- add patch request to modify item quantity
- delete request to delete individual item
- delete request to clear shopping cart of all items
<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. (drag & drop 또는 첨부파일 추가)
<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

<br />

2023-06-02 10:09 UTC, kyeongraekim requested changes

2023-06-02 10:09 UTC, kyeongraekim commented on controllers/cartsController.js
> +  //const {userId} = req.body
- 해당 내용은 auth 코드에 대한 인가를 위해서 잠시 보류해둔 상태이신거죠?
- 주석 처리된 부분은 삭제해주시고, 곧머지될 관용님 코드 내 auth 코드가 병합된 이후의 상황을 가정해서 코드를 작성해주세요!

2023-06-02 10:09 UTC, kyeongraekim commented on controllers/cartsController.js
> +  const userId = req.headers.userid
- userId는 req 객체에 user라는 변수안에 담길 예정입니다. 아래의 내용이 더 맞을 것 같네요!

```javascript
const userId = req.user

2023-06-02 10:09 UTC, kyeongraekim commented on controllers/cartsController.js
> +  console.log(existingItem)
- 불필요한 콘솔로깅은 푸시 전에 삭제해주세요!

2023-06-02 10:09 UTC, kyeongraekim commented on controllers/cartsController.js
> +  return res.status(201).json({
- update에 대한 상태코드는 201이 아닌 200으로 설정해주세요! 자원의 생성이 아닌 수정의 개념으로 봐주시면 되겠습니다!

2023-06-02 10:09 UTC, kyeongraekim commented on routers/index.js
> +  const dogAscii = `
- 강아지가 귀엽네요!

2023-06-02 10:09 UTC, kyeongraekim commented on routers/cartsRouter.js
> +cartsRouter.delete('/remove', cartController.deleteItemInCart)
자명하게 표현해야하는 엔드포인트에서, + / - 1의 표현을 해야함으로 어쩔 수 없이 쓰는 동사어구뒤에는 리소스적인 차원의 내용을 풀어주세요!

```javascript
patch('/add/single-item')
patch('/subtract/single-item')
patch('/remove/all-items')

2023-06-02 10:09 UTC, kyeongraekim commented on models/cartsDao.js
> +}
- 전체적으로 훑어봐주시고, 재고이상의 수량을 원할 때 불가함을 내는 에러핸들링을 추가해주세요!

2023-06-02 10:09 UTC, kyeongraekim commented on models/cartsDao.js
> +const queryDeleteItemInCart = async (userId, productId) => {
- item을 삭제하는 내용인데 SQL문의 delete문이 쓰여야 할 것 같네요!

2023-06-02 10:09 UTC, kyeongraekim commented on controllers/cartsController.js
> +  const productId = req.body.productId
- delete에 해당되는 내용은 path parameter를 사용해주세요!

- req.params에 접근하여 원하는 데이터를 뽑아 오게끔 해야 되겠네요!

2023-06-05 06:27 UTC, Jon9Beom commented on routers/index.js
> +router.use('/shopping-cart', cartsRouter)
```suggestion
router.use('/products', productsRouter)
router.use('/shopping-carts', cartsRouter)
```
사소하다고 생각될 수 있지만 복수, 단수도 일괄적으로 맞춰주시는게 좋습니다 :)
(ex. `/shopping-carts`, `/carts`)

2023-06-05 06:27 UTC, Jon9Beom commented on routers/productsRouter.js
> +import { productController } from '../controllers/index.js'
일반적인 module import 컨벤션에 따라, 외부 모듈과 custom 모듈 간 줄바꿈을 활용해 구분지어주시면 더 좋을 것 같습니다~
```suggestion
import { Router } from 'express'

import { productController } from '../controllers/index.js'
```

2023-06-05 06:27 UTC, Jon9Beom commented on routers/productsRouter.js
> +productsRouter.get('/', productController.getProducts)
```suggestion
productsRouter.get('', productController.getProducts)
```
REST architecture의 여러 원칙중 안티패턴을 줄이고 REST를 사용하는 개발자들이 통일된 포맷의 엔드포인트를 작성할 수 있도록 정의한 uniform interface 원칙에 의하면 엔드포인트 끝에는 `/`를 사용하는 것을 지양하도록 하고 있습니다. 

이러한 부분도 크리티컬하진 않지만 REST를 배우고 이해하며 적용한 프로젝트이기에 
이에 따라 수정하면 좋을 것 같습니다~!

cartsRouter.js 같은 모듈에도 적용될 수 있는 부분을 찾아 수정부탁드리겠습니다. :)

2023-06-05 06:27 UTC, Jon9Beom commented on services/cartsService.js
> +}
```suggestion
const getCartItems = async (userId) => {
  return queryCartItems(userId)
}
```
작성해주신 코드 이외에 별다른 로직이 들어가지 않는다면 변수 선언과 비동기처리 없이 곧바로 return 해주시는것이 보다 더 깔끔한 코드가 될 수 있습니다!

다른부분들도 일괄 적용 부탁드리겠습니다~

2023-06-05 10:01 UTC, closed without merging