Feature/auth
wecode-bootcamp-korea/46-1st-WePet-backend pull request #5
Opened 2023-06-02 09:45 UTC by lee-kwanyong

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.
- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?

  (예시) 고객의 유입과 전환을 책임지는 회원 기능에서, 유저의 이탈을 방지하기 위해 input 창 바로 아래에서 실시간으로 적색의 경고 메세지를 전달 받습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

  (예시) 유저는 실시간으로 스스로 오기입한 내용을 확인할 수 있기 때문에 잘못 계정 정보를 작성함으로써 발생될 수 있는 변수를 최소화할 수 있습니다. 이는 곧 유저 전환의 허들을 낮추어 줄 수 있습니다.

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 그리고 상세 내역을 적어주세요.

회원가입 기능추가
로그인 기능 추가 - 토큰발급

- (예시) email입력 `@`필요,password에 숫자로 8자이상 유효성 검사 추가
- (예시) 유효성 검사 통과시 버튼 컬러 변경 및 버튼 활성화

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. (drag & drop 또는 첨부파일 추가)
<br />

-

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- (예시) 새로운 배열메서드 filter를 쓸 수 있게됐습니다.
- (예시) 상수데이터와 map 메서드로 반복되는 UI를 그릴 수 있게 됐습니다.
- (예시) fetch함수를 어떻게 쓰는지 알게됐습니다.
- (예시) 계산된 속성명 (computed property)을 쓰긴했는데 어떻게 돌아가는지 이해가 잘 안되서
  블로그에 정리해봐야겠습니다.
- (예시) 화살표 함수(arrow-function) 어떤 코드를 언제 생략할 수있는지 완벽 이해했습니다.
- (예시) 구조분해할당(Destructuring assignment)을 써보니 가독성도, 유지보수도 편할것같습니다.
  <br />

2023-06-02 10:14 UTC, kyeongraekim requested changes

2023-06-02 10:14 UTC, kyeongraekim commented on app.js
> +app.use(morgan("dev"))
- app.use(cors()) 와 morgan 부분이 잘못 추가되어잇네요 삭제해주세요!

2023-06-02 10:14 UTC, kyeongraekim commented on controllers/usersController.js
> +//회원가입
- 전체적으로 불필요한 주석 설명문을 삭제해주세요!
- 상용화될 코드로의 푸시에서는 불필요한 작업입니다.

2023-06-02 10:14 UTC, kyeongraekim commented on utils/auth.js
> +import verify from 'jsonwebtoken'
- 전체적으로 불필요한 주석문 살펴주시고 삭제해주세요!

2023-06-05 05:59 UTC, Jon9Beom commented on app.js
> +app.use(morgan("dev"))
관용님~ 이부분 이전 피드백이 반영이 안되어있네요! 확인 부탁드리겠습니다~
```suggestion
```

2023-06-05 05:59 UTC, Jon9Beom commented on utils/auth.js
> +import verify from 'jsonwebtoken'
이부분도 마찬가지로 이전에 경래님이 남겨주신 리뷰가 반영이 안되어 있네요!
> - 전체적으로 불필요한 주석문 살펴주시고 삭제해주세요!
- 불필요한 주석은 삭제해주세요!
- 코드에 대한 설명을 주석으로 남겨놓고 싶어서 주석을 달게 되는 것은 처음에는 좋아보일 수는 있으나 나중에 코드에 수정이 발생했을 때 설명하는 주석까지 같이 수정하는 것을 놓치게 된다면 결국 설명 주석과 코드의 내용이 달라지고 오히려 더 유지보수하기 힘들게 될 수 있습니다.
- 주석으로 코드를 설명하기보다는 코드 자체의 가독성이 좋게만들어서 부가적인 설명이 필요없는 코드로 만들어주세요!

2023-06-05 05:59 UTC, Jon9Beom commented on models/usersDao.js
> +// }
사용하지 않는 코드라면 주석처리로 남겨놓기보다 지워서 올라올 수 있도록 해주세요~
merge가 되면서 쌓이는 작업물들이 실제 다음 커리어를 위한 포트폴리오로써 활용되는데 불필요한 주석 및 콘솔로그가 남아있으면 추후에 정리를 위한 작업이 추가로 필요하게 됩니다 :)

2023-06-07 01:15 UTC, closed without merging